### ISSUE TITLE
Improve -onlydesc option in rfci 

### ISSUE THREAD

**Issue by kalvari** [Rfam/rfam-family-pipeline#11]
Committing old families with `-onlydesc` option currently raises a Full_Region error due to QC. The QC tries to match hits in the full_region table with hits in the outlist and tblout files of the family. The QC will fail for families that were build from old sequence databases, as those hits have been replaced by hits from the most recent genome searches. We need to either disable this or limit it to new families only by including an additional option in rfci

**Comment by kalvari** [comment]
This will be resolved with issue #29

**Comment by AntonPetrov** [comment]
This is resolved by the switch to the new rfci-md5 paradigm. Closing ✅
