### ISSUE TITLE
Find new HCV families and review packaging signals

### ISSUE THREAD

**Issue by kalvari** [Rfam/rfam-family-pipeline#18]
Family RF02585 - could be a signal to start replication

**Comment by JoannaArgasinska** [comment]
Found papers for Emerge: 18480457, 29367245,  26867128 , 
Reviews 25576644 -cis-Acting RNA elements in the hepatitis C virus RNA genome.2015
28511116 Functional RNA structures throughout the Hepatitis C Virus genome.2017

**Comment by JoannaArgasinska** [comment]
25964384

**Comment by AntonPetrov** [comment]
The HCV families will be updated as part of collaboration with [EVBC](http://evbc.uni-jena.de) so closing this issue.
