### ISSUE TITLE
Re-threshold RF00857 

### ISSUE THREAD

**Issue by kalvari** [Rfam/rfam-family-pipeline#30]
According to Sam's suggestions, mir-233 (RF00857) requires re-thresholding with cutoff set to 52.10 to get rid of any sequences that aren't _C.elegans_

**Comment by kalvari** [comment]
This issue is dependent on the MD5 QC code

**Comment by AntonPetrov** [comment]
[RF00857](https://rfam.org/family/RF00857#tabview=tab4) has been updated with a miRBase seed alignment and now includes only _Caenorhabditis_ seed and full sequences.
