### ISSUE TITLE
Fix duplicated regions in SEEDSCORES files

### ISSUE THREAD

**Issue by kalvari** [Rfam/rfam-family-pipeline#52]
The current version of the code oddly misbehaves by appending a second pair of coordinates to the already existing ones in the SEEDSCORES files. 

Example from the `RF00050` SEEDSCORES file:
```
ABCH01000022.1/43466-43613/1-148    1  148  ABCH01000022.1/43466-43613    133.2  2.1e-27   1  140  0  seed
AAKK02000001.1/258130-258269/1-140  1  140  AAKK02000001.1/258130-258269  132.1  4.1e-27   1  140  0  seed
AE016796.2/1572120-1571980/1-141    1  141  AE016796.2/1572120-1571980    131.7  5.3e-27   1  140  0  seed
AAWP01000010.1/3949-3809/1-141      1  141  AAWP01000010.1/3949-3809      130.9  8.7e-27   1  140  0  seed
AANE01000019.1/87182-87037/1-146    1  146  AANE01000019.1/87182-87037    130.6    1e-26   1  140  0  seed
```

**Comment by nawrockie** [comment]
Do you have examples where it doesn't do this?

**Comment by kalvari** [comment]
Yes. For most of the cases. This is an odd one. We committed >500 families without any issues, this is why I am also suspecting something gone wrong during curation.

**Comment by kalvari** [comment]
Resolved by @nawrockie 

This is not a bug, but the new labeling in SEEDSCORES accommodating the most recent code updates.
