### ISSUE TITLE
Update ZWD families missing pseudoknots

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-family-pipeline#69]
A while back (see RT #282705) Zasha reported that some of his families are missing pseudoknots. I suggest updating the following families using the original ZWD alignments with RNAcentral IDs, as discussed in the Rfam 14 NAR paper.

Here are the families: 
For more information relate to this updates
https://docs.google.com/spreadsheets/d/1JTZwtmNm6Zrozm4H7oYMWWBAj9CZPLeX20eF9yV9PbA/edit?usp=sharing
- [x] RF01689|AdoCbl-variant
- [x] RF01696|Chlorobi-1
- [x] RF01734|crcB
- [x] RF01704|Downstream-peptide
- [x] RF01735|epsC
- [x] RF01739|glnA
- [x] RF01745|manA
- [x] RF01750|pfl
- [x] RF01717|PhotoRC-II
- [x] RF01754|radC
- [x] RF01725|SAM-I-IV-variant
- [x] RF01728|STAXI
- [x] RF01761|wcaG
- [x] RF01763|ykkC-III
- [x] RF02032 GOLLD
- [x] RF02033 HEARO
- [x] RF02034 IMES-1
- [x] RF02035 IMES-2

You can find all ZWD alignments with RNAcentral IDs here:
https://www.dropbox.com/s/7q7r3bairt3s4in/zwd-rnacentral-ids.zip?dl=0

Please note that some of the families could have been already fixed.

**Comment by nancyontiveros** [comment]
✍️

**Comment by nancyontiveros** [comment]
12 families has been updated, 1 family manA was already updated.

RF01717\|PhotoRC-II
RF01754\|radC
RF01728\|STAXI
RF02034 IMES-1
RF02033 HEARO
RF01745\|manA
RF01761\|wcaG
RF01735\|epsC
RF01763\|ykkC-III
RF01734\|crcB
RF01704\|Downstream-peptide
RF01750\|pfl

Other 7 families have different issues

RF01820 : Overlaps with RF01485 and RF01858
RF01725\|SAM-I-IV-variant : SEED need to be edited, to add the 3D information
RF01696\|Chlorobi-1 : This family do not present PKs, not need to be updated
RF01739\|glnA : Error on the commit ( Error running RNAcode: 256 / QC.pm line 1747)
RF01689\|AdoCbl-variant: We trim this region, may not need to be update)
RF02032 GOLLD : RF not correct
RF02035 IMES-2 :  Error on the commit ( md5 / QC.pm)
